#!/usr/bin/env groovy
pipeline {
    agent {
        kubernetes {
            label 'zehuabuildpod'
            yamlFile 'k8s/KubernetesPod.yaml'
        }
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    echo 'Building..'
                    echo "${env.WORKSPACE}"
                    echo "${env.PWD}"
                    sh 'mvn -U -Dmaven.test.failure.ignore=true clean package'
                }
            }
            post {
                success {
                    junit '**/target/surefire-reports/**/*.xml'
                }
            }
        }
    }
}
