metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: maven
      image: maven:3.6.1
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: maven
    - name: busybox
      image: busybox
      command:
        - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: busybox